---
- name: Create Realm OS group
  group:
    name: ros
    gid: 2011

- name: Create Realm OS user
  user:
    name: ros
    comment: Realm OS
    uid: 2011
    group: ros

- name: Install Python pip
  yum:
    name: python2-pip
    state: present

- name: Install pexpect to support Ansible expect module
  pip:
    name: pexpect
    state: present

- name: Download Node.js Yum Repo Setup Script
  get_url:
    url="https://rpm.nodesource.com/setup_8.x"
    dest=/root/setup_8.x
    mode=700

- name: Add Node.js Repository
  command: /root/setup_8.x

- name: Install Node.js
  yum:
    name: nodejs
    state: present

- name: Install Realm
  npm:
    name: realm-object-server
    path: /home/ros
  become: yes
  become_user: ros

- name: Initialize Realm
  expect: 
    command: /home/ros/node_modules/.bin/ros init FAST-ROS-Production
    responses:
       Agree with your email: "cpkampmeier@gmail.com"
       Would you like to receive: "N"
  args:
    chdir: /home/ros
  become: yes
  become_user: ros

- name: Install AWS Cognito mobile user management
  npm:
    name: realm-object-server-cognito-auth
    path: /home/ros/FAST-ROS-Production
  become: yes
  become_user: ros

- name: Configure Realm service
  template:
    src: templates/index.ts.j2
    dest: /home/ros/FAST-ROS-Production/src/index.ts
    owner: ros
    group: ros
    mode: 0644

- name: Configure Realm Startup Script
  template:
    src: templates/start.sh.j2
    dest: /home/ros/FAST-ROS-Production/start.sh
    owner: ros
    group: ros
    mode: 0744

- name: Configure Realm system service
  template:
    src: templates/ros.service.j2
    dest: /lib/systemd/system/ros.service
    owner: root
    group: root
    mode: 0644

- name: Reload Realm OS service
  service:
    name: ros
    state: reloaded

- name: Start Realm OS service
  service:
    name: ros
    state: started
#
# ros backup -f FAST-ROS-Production -t ./ROS-Backups
# 
# Enable disk volume growth:
# lsblk
# sudo growpart /dev/xvda 1
# lsblk
# sudo yum install xfsprogs
# sudo xfs_growfs -d /dev/xvda1