---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: serverspec

platforms:
  - name: centos
    driver_config:
      image: centos:7

suites:
  - name: default
